'use strict';

const path = require('path');
const fs = require('fs-extra');

async function run(a) {
  const isTs = a.language === 'typescript';
  const tsx = isTs ? 'tsx' : 'js';
  const appPath = path.join(a.targetDir, `App.${tsx}`);

  // Delete other App file if it exists to avoid conflicts
  const otherAppPath = path.join(a.targetDir, `App.${isTs ? 'js' : 'tsx'}`);
  await fs.remove(otherAppPath);

  // If JS, also delete tsconfig.json
  if (!isTs) {
    await fs.remove(path.join(a.targetDir, 'tsconfig.json'));
  }

  const imports = [
    "import React from 'react';",
    "import { StatusBar, useColorScheme } from 'react-native';",
    "import { SafeAreaProvider } from 'react-native-safe-area-context';",
    "import { ThemeProvider } from './src/theme/ThemeProvider';",
  ];

  // localization i18n
  imports.push("import './src/localization/i18n';");

  if (a.stateManagement.includes('redux-toolkit')) {
    imports.push("import { Provider as ReduxProvider } from 'react-redux';");
    imports.push("import { store } from './src/store/store';");
    if (a.stateManagement.includes('redux-persist')) {
      imports.push("import { PersistGate } from 'redux-persist/integration/react';");
      imports.push("import { persistor } from './src/store/store';");
    }
  }

  if (a.stateManagement.includes('react-query')) {
    imports.push("import { QueryClientProvider } from '@tanstack/react-query';");
    imports.push("import queryClient from './src/store/queryClient';");
  }

  if (a.stateManagement.includes('context')) {
    imports.push("import { AppProvider } from './src/store/AppContext';");
  }

  const hasRootNav = a.navigation.includes('root');
  if (hasRootNav) {
    imports.push("import RootNavigator from './src/navigation/RootNavigator';");
  } else {
    imports.push("import { View, Text } from 'react-native';");
  }

  let renderContent = '';
  if (hasRootNav) {
    renderContent = '<RootNavigator />';
  } else {
    renderContent = `
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Welcome to ${a.displayName || a.projectName}!</Text>
      </View>
    `;
  }

  let wrapStart = '';
  let wrapEnd = '';
  let indent = '';

  if (a.stateManagement.includes('redux-toolkit')) {
    wrapStart += `${indent}<ReduxProvider store={store}>\n`;
    wrapEnd = `\n${indent}</ReduxProvider>` + wrapEnd;
    indent += '  ';
    if (a.stateManagement.includes('redux-persist')) {
      wrapStart += `${indent}<PersistGate loading={null} persistor={persistor}>\n`;
      wrapEnd = `\n${indent}</PersistGate>` + wrapEnd;
      indent += '  ';
    }
  }

  if (a.stateManagement.includes('react-query')) {
    wrapStart += `${indent}<QueryClientProvider client={queryClient}>\n`;
    wrapEnd = `\n${indent}</QueryClientProvider>` + wrapEnd;
    indent += '  ';
  }

  if (a.stateManagement.includes('context')) {
    wrapStart += `${indent}<AppProvider>\n`;
    wrapEnd = `\n${indent}</AppProvider>` + wrapEnd;
    indent += '  ';
  }

  wrapStart += `${indent}<ThemeProvider>\n`;
  wrapStart += `${indent}  <SafeAreaProvider>\n`;
  wrapStart += `${indent}    <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />\n`;
  wrapStart += `${indent}    ${renderContent.trim()}`;

  wrapEnd = `\n${indent}  </SafeAreaProvider>\n${indent}</ThemeProvider>` + wrapEnd;

  // Indent the wrap codes inside return()
  const wrappedBody = `  const isDarkMode = useColorScheme() === 'dark';\n\n  return (\n${wrapStart.split('\n').map(line => '    ' + line).join('\n')}\n${wrapEnd.split('\n').map(line => '    ' + line).join('\n')}\n  );`;

  const content = `/**\n * Generated by lakshit-rn-cli\n */\n\n${imports.join('\n')}\n\nexport default function App() {\n${wrappedBody}\n}\n`;

  await fs.writeFile(appPath, content);
}

module.exports = { run };
