'use strict';

const path = require('path');
const fs = require('fs-extra');

async function run(a) {
  await fs.writeFile(
    path.join(a.targetDir, 'README.md'),
    `# ${a.displayName}

${a.copyright}

Generated by **rn-enterprise-cli**.

## Stack
- Language: ${a.language === 'typescript' ? 'TypeScript' : 'JavaScript'}
- Package manager: ${a.packageManager}
- Architecture: ${a.architecture}
- State management: ${a.stateManagement.join(', ') || 'none'}
- Firebase modules: ${a.useFirebase ? a.firebaseModules.join(', ') || 'none selected' : 'not included'}
- Auth methods: ${a.authMethods.join(', ')}
- Security features: ${a.security.join(', ') || 'none'}
- Offline-first: ${a.offlineFirst ? 'yes' : 'no'}
- Notifications: ${a.notifications ? 'yes' : 'no'}
- Locales: ${a.locales.join(', ')}${a.rtl ? ' (RTL enabled)' : ''}

## Getting started
See [GETTING_STARTED.md](./GETTING_STARTED.md).

## Architecture
See [ARCHITECTURE.md](./ARCHITECTURE.md).

## Security
See [SECURITY.md](./SECURITY.md) for what's enabled and why.

## Generating new code
\`\`\`bash
rn-enterprise generate screen ProductDetails --feature catalog
rn-enterprise generate service PaymentsApi
rn-enterprise generate component PriceTag
rn-enterprise generate module Checkout
\`\`\`

## Roadmap
See [ROADMAP.md](./ROADMAP.md).
`
  );

  await fs.writeFile(
    path.join(a.targetDir, 'GETTING_STARTED.md'),
    `# Getting Started

## 1. Install dependencies
\`\`\`bash
${a.packageManager} install
cd ios && pod install && cd ..   # iOS only
\`\`\`

## 2. Configure environments
Real secrets go in \`.env.development\`, \`.env.qa\`, \`.env.staging\`, \`.env.production\`
(generated with placeholders — never commit real values). \`.env.example\` shows the shape.

## 3. Native setup
Follow:
- \`android_config_notes/MANIFEST_CHECKLIST.md\`
- \`ios_config_notes/INFO_PLIST_CHECKLIST.md\`

${a.useFirebase ? `## 4. Firebase\nAdd \`google-services.json\` (Android) and \`GoogleService-Info.plist\` (iOS) per environment from the Firebase console.\n\n` : ''}## Run the app
\`\`\`bash
${a.packageManager} run android
${a.packageManager} run ios
\`\`\`

## Run tests
${a.testing.includes('jest') ? `\`\`\`bash\n${a.packageManager} run test\n\`\`\`\n` : '_No test runner selected._'}
${a.testing.includes('detox') ? `\`\`\`bash\n${a.packageManager} run test:e2e\n\`\`\`\n` : ''}
`
  );

  const archNotes = {
    'clean-architecture': `Clean Architecture separates the app into three layers:

- **domain/** — entities and use cases, pure business logic, no React Native or Firebase imports.
- **data/** — repository implementations and datasources (remote/local) that satisfy domain interfaces.
- **presentation/** — screens, viewmodels, and components that consume use cases.

Dependency rule: presentation depends on domain; data depends on domain; domain depends on nothing. This keeps business logic testable without mocking React Native.`,
    mvvm: `MVVM splits the app into:

- **models/** — plain data shapes.
- **viewmodels/** — hold screen state and orchestrate repositories; no JSX.
- **views/** — screens and components that render a viewmodel's state.
- **repositories/** — data access, called only from viewmodels.`,
    'feature-based': `Feature-based/Modular organizes code by product feature rather than technical layer:

- **features/<name>/screens**, **components**, **services** — everything a feature needs lives together.
- **components/ui** — cross-feature shared design-system components only.
- Shared cross-cutting concerns (auth, security, networking, state) live at \`src/services\` and \`src/store\`, imported by any feature.`,
  };

  await fs.writeFile(
    path.join(a.targetDir, 'ARCHITECTURE.md'),
    `# Architecture: ${a.architecture}

${archNotes[a.architecture] || ''}

## Folder map
\`\`\`
src/
  app/            bootstrap, providers, root component
  config/         env loader
  navigation/     root/auth/main navigators, deep linking, guards
  theme/          colors, spacing, typography, ThemeProvider
  components/ui/  shared design-system components
  store/          state management (${a.stateManagement.join(', ')})
  services/
    api/          axios client, interceptors, repository pattern
    firebase/     Firebase module wrappers
    auth/         unified authService across providers
    security/     token storage, encryption, device integrity, pinning
    storage/      MMKV / keychain helpers
    notifications/ FCM + local notifications
    offline/      cache, mutation queue, background sync, conflict handling
  localization/   i18next setup, locale JSON, RTL, a11y helpers
\`\`\`

## Repository Pattern
Screens/viewmodels never call \`axios\`/Firebase SDKs directly — they call a repository
(e.g. \`src/services/api/exampleRepository\`) that hides the data source. Swapping REST
for GraphQL, or adding an offline cache layer, only touches the repository.
`
  );

  await fs.writeFile(
    path.join(a.targetDir, 'ROADMAP.md'),
    `# Roadmap

## v1 (this generated project)
- Project configuration, environments, ${a.architecture} scaffolding
- ${a.stateManagement.join(', ') || 'no'} state management wired up
- ${a.useFirebase ? a.firebaseModules.length : 0} Firebase module(s), ${a.authMethods.length} auth method(s)
- Security baseline: ${a.security.join(', ') || 'secure token storage only'}
- Navigation (${a.navigation.join(', ')}), UI kit, localization (${a.locales.join(', ')})
- Offline-first: ${a.offlineFirst ? 'enabled' : 'not enabled'}; Notifications: ${a.notifications ? 'enabled' : 'not enabled'}
- Testing: ${a.testing.join(', ') || 'none'}; Code quality: ${a.codeQuality.join(', ') || 'none'}
- CI: ${a.githubActions ? 'GitHub Actions' : 'none'}; Fastlane: ${a.fastlane ? 'yes' : 'no'}

## v2 (suggested next)
- Design token sync from Figma into \`src/theme\`
- Automated visual regression testing (e.g. Percy/Chromatic equivalents for RN)
- Server-driven feature flags beyond Remote Config (e.g. gradual rollouts, kill switches)
- Modularize \`node_modules\` boundaries with a monorepo (Nx/Turborepo) if multiple apps share code
- Formal MFA enrollment flow (the current auth service only stubs \`verifySecondFactor\`)
- Expand offline conflict resolution from function-based to a full sync-engine (e.g. CRDT-based)

## v3 (longer-term)
- Codegen from OpenAPI/GraphQL schema straight into the repository layer
- Plugin marketplace: let teams publish/install third-party generators (see PLUGINS.md)
- White-label support: multiple \`app.config.js\` variants built from one codebase
- Automated dependency + native-module upgrade tooling (react-native upgrade helper integration)
- Performance budgets enforced in CI (bundle size, cold start time regression checks)
`
  );

  await fs.writeFile(
    path.join(a.targetDir, 'PLUGINS.md'),
    `# Plugin & Custom Generator Architecture

The CLI's \`generate\` command (\`rn-enterprise generate <type> <name>\`) is built around
a simple plugin contract so teams can add their own generators without forking the CLI:

\`\`\`js
// plugins/my-generator.js
module.exports = {
  type: 'redux-module', // used as: rn-enterprise generate redux-module <name>
  async generate({ name, targetDir, answers }) {
    // write files using fs-extra, same as the built-in generators
  },
};
\`\`\`

Register plugins in \`.rn-enterprise/plugins.json\` at the project root:
\`\`\`json
{ "plugins": ["./plugins/my-generator.js"] }
\`\`\`

The built-in generator loader (src/generators/customGenerator.js) checks this file
before falling back to its built-in screen/module/service/component templates.
`
  );
}

module.exports = { run };
