'use strict';

const path = require('path');
const fs = require('fs-extra');

/**
 * Native Android/iOS projects are generated by `react-native init` /
 * community CLI templates, not by this tool. Instead of guessing at Gradle
 * file contents (fragile across RN versions), this generator writes precise,
 * copy-pasteable config snippets + a checklist so each selection in the
 * wizard maps to a concrete native step.
 */
async function run(a) {
  const androidDir = path.join(a.targetDir, 'android_config_notes');
  const iosDir = path.join(a.targetDir, 'ios_config_notes');

  const permissions = [];
  if (a.notifications) permissions.push('POST_NOTIFICATIONS (Android 13+)', 'Push notification capability (iOS)');
  if (a.authMethods.includes('biometric')) permissions.push('USE_BIOMETRIC / USE_FINGERPRINT (Android)', 'Face ID usage description (iOS Info.plist: NSFaceIDUsageDescription)');
  if (a.authMethods.includes('phone') || a.authMethods.includes('otp')) permissions.push('READ_PHONE_STATE (optional, Android)');
  permissions.push('INTERNET (Android, default)');

  await fs.writeFile(
    path.join(androidDir, 'MANIFEST_CHECKLIST.md'),
    `# Android Manifest & Gradle Checklist

Generated for: **${a.projectName}** (package: \`${a.androidPackage}\`)

## Permissions to add to android/app/src/main/AndroidManifest.xml
${permissions.map((p) => `- ${p}`).join('\n')}

## Package name
Set \`applicationId "${a.androidPackage}"\` in android/app/build.gradle.

## Version
\`\`\`gradle
versionCode ${a.buildNumber}
versionName "${a.version}"
\`\`\`

${
  a.useFirebase
    ? `## Firebase
1. Download google-services.json from the Firebase console for each environment (dev/qa/staging/prod) and place per-flavor, or use a single project with environment suffixing.
2. Add to android/build.gradle: classpath 'com.google.gms:google-services:4.4.2'
3. Add to android/app/build.gradle (bottom): apply plugin: 'com.google.gms.google-services'
`
    : ''
}${
  a.navigation.includes('deep-linking')
    ? `## Deep Linking intent-filter (add inside the launcher <activity>)
\`\`\`xml
<intent-filter android:autoVerify="true">
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="${a.projectName}" />
  <data android:scheme="https" android:host="${(a.website || 'example.com').replace(/^https?:\/\//, '')}" />
</intent-filter>
\`\`\`
`
    : ''
}## Splash Screen
Use react-native-bootsplash or the community Splash Screen API; place your logo under android/app/src/main/res/drawable-*.

## Signing
Add a release signing config placeholder in android/app/build.gradle:
\`\`\`gradle
signingConfigs {
  release {
    storeFile file(System.getenv("ANDROID_KEYSTORE_PATH") ?: "release.keystore")
    storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
    keyAlias System.getenv("ANDROID_KEY_ALIAS")
    keyPassword System.getenv("ANDROID_KEY_PASSWORD")
  }
}
\`\`\`
Never commit the actual keystore or passwords — inject via CI secrets.
`
  );

  await fs.writeFile(
    path.join(iosDir, 'INFO_PLIST_CHECKLIST.md'),
    `# iOS Info.plist & Podfile Checklist

Generated for: **${a.projectName}** (bundle id: \`${a.iosBundleId}\`)

## Bundle identifier & version
Set in Xcode (or ios/${a.projectName}.xcodeproj/project.pbxproj):
- PRODUCT_BUNDLE_IDENTIFIER = ${a.iosBundleId}
- MARKETING_VERSION = ${a.version}
- CURRENT_PROJECT_VERSION = ${a.buildNumber}

## Permissions (Info.plist usage descriptions)
${permissions
  .filter((p) => p.includes('iOS') || p.includes('Face ID'))
  .map((p) => `- ${p}`)
  .join('\n') || '- (none beyond defaults)'}

${
  a.useFirebase
    ? `## Firebase
1. Download GoogleService-Info.plist per environment from the Firebase console.
2. Add the Firebase pods via \`pod install\` after adding the RN Firebase packages to package.json (already generated).
`
    : ''
}${
  a.notifications
    ? `## Push Notifications
1. Enable "Push Notifications" and "Background Modes > Remote notifications" capabilities in Xcode.
2. Upload your APNs key/certificate to the Firebase console (Messaging) or your push provider.
`
    : ''
}${
  a.navigation.includes('deep-linking')
    ? `## Associated Domains (Universal Links)
Add to the app's entitlements:
\`\`\`
applinks:${(a.website || 'example.com').replace(/^https?:\/\//, '')}
\`\`\`
And URL scheme \`${a.projectName}\` under Info > URL Types for custom-scheme deep links.
`
    : ''
}## Podfile
Run \`cd ios && pod install\` after every native dependency change. Ensure \`use_frameworks!\` matches the config required by Firebase pods if you enabled Firebase.
`
  );
}

module.exports = { run };
